In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.svm import SVC  
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.decomposition import FastICA
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import decomposition
from sklearn.feature_selection import SelectPercentile as sp
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import Lasso
from mlxtend.feature_selection import SequentialFeatureSelector
from sklearn.feature_selection import RFECV
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv('Linux_process_1.csv')

In [3]:
df.head()

,ts,PID,TRUN,TSLPI,TSLPU,POLI,NICE,PRI,RTPR,CPUNR,Status,EXC,State,CPU,CMD,label,type
0,1554218915,3257,0,23,0,norm,0,120,0,2,N,0,S,0.13,Web-Content,0,normal
1,1554218920,1442,0,1,0,norm,0,120,0,0,N,0,S,0.09,Xorg,0,normal
2,1554218925,3197,0,63,0,norm,0,120,0,3,N,0,S,0.06,firefox,0,normal
3,1554218930,2774,0,8,0,norm,0,120,0,0,N,0,S,0.06,compiz,0,normal
4,1554218935,2797,0,5,0,norm,0,120,0,0,N,0,S,0.04,nautilus,0,normal

In [4]:
df = df.drop(['ts', 'PID'], axis = 1)
df

,TRUN,TSLPI,TSLPU,POLI,NICE,PRI,RTPR,CPUNR,Status,EXC,State,CPU,CMD,label,type
0,0,23,0,norm,0,120,0,2,N,0,S,0.13,Web-Content,0,normal
1,0,1,0,norm,0,120,0,0,N,0,S,0.09,Xorg,0,normal
2,0,63,0,norm,0,120,0,3,N,0,S,0.06,firefox,0,normal
3,0,8,0,norm,0,120,0,0,N,0,S,0.06,compiz,0,normal
4,0,5,0,norm,0,120,0,0,N,0,S,0.04,nautilus,0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0,normal
999996,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0,normal
999997,0,1,0,norm,0,120,0,0,-,0,S,0.00,apache2,0,normal
999998,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0,normal
999999,0,2,0,norm,0,120,0,0,-,0,S,0.00,vmtoolsd,0,normal

In [5]:
df.isnull().sum()

TRUN      0
TSLPI     0
TSLPU     0
POLI      0
NICE      0
PRI       0
RTPR      0
CPUNR     0
Status    0
EXC       0
State     0
CPU       0
CMD       0
label     0
type      0
dtype: int64

In [6]:
target = df.loc[:, ('type')]

In [7]:
df = df.drop('type', axis = 1)
df

,TRUN,TSLPI,TSLPU,POLI,NICE,PRI,RTPR,CPUNR,Status,EXC,State,CPU,CMD,label
0,0,23,0,norm,0,120,0,2,N,0,S,0.13,Web-Content,0
1,0,1,0,norm,0,120,0,0,N,0,S,0.09,Xorg,0
2,0,63,0,norm,0,120,0,3,N,0,S,0.06,firefox,0
3,0,8,0,norm,0,120,0,0,N,0,S,0.06,compiz,0
4,0,5,0,norm,0,120,0,0,N,0,S,0.04,nautilus,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0
999996,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0
999997,0,1,0,norm,0,120,0,0,-,0,S,0.00,apache2,0
999998,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0
999999,0,2,0,norm,0,120,0,0,-,0,S,0.00,vmtoolsd,0

In [8]:
cat = []
for i in df.columns:
    if len(df[i].unique()) <= 328: cat.append(i)
df_cat = df[cat]
df_cat

,TRUN,TSLPI,TSLPU,POLI,NICE,PRI,RTPR,CPUNR,Status,EXC,State,CPU,CMD,label
0,0,23,0,norm,0,120,0,2,N,0,S,0.13,Web-Content,0
1,0,1,0,norm,0,120,0,0,N,0,S,0.09,Xorg,0
2,0,63,0,norm,0,120,0,3,N,0,S,0.06,firefox,0
3,0,8,0,norm,0,120,0,0,N,0,S,0.06,compiz,0
4,0,5,0,norm,0,120,0,0,N,0,S,0.04,nautilus,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0
999996,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0
999997,0,1,0,norm,0,120,0,0,-,0,S,0.00,apache2,0
999998,0,1,0,norm,0,120,0,3,-,0,S,0.00,apache2,0
999999,0,2,0,norm,0,120,0,0,-,0,S,0.00,vmtoolsd,0

In [9]:
label_encoder = preprocessing.LabelEncoder()
df['Status'] = label_encoder.fit_transform(df['Status'])
df['POLI'] = label_encoder.fit_transform(df['POLI'])
df['State'] = label_encoder.fit_transform(df['State'])
df['CMD'] = label_encoder.fit_transform(df['CMD'])

In [10]:
df

,TRUN,TSLPI,TSLPU,POLI,NICE,PRI,RTPR,CPUNR,Status,EXC,State,CPU,CMD,label
0,0,23,0,2,0,120,0,2,3,0,3,0.13,153,0
1,0,1,0,2,0,120,0,0,3,0,3,0.09,155,0
2,0,63,0,2,0,120,0,3,3,0,3,0.06,197,0
3,0,8,0,2,0,120,0,0,3,0,3,0.06,177,0
4,0,5,0,2,0,120,0,0,3,0,3,0.04,275,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,1,0,2,0,120,0,3,0,0,3,0.00,160,0
999996,0,1,0,2,0,120,0,3,0,0,3,0.00,160,0
999997,0,1,0,2,0,120,0,0,0,0,3,0.00,160,0
999998,0,1,0,2,0,120,0,3,0,0,3,0.00,160,0
999999,0,2,0,2,0,120,0,0,0,0,3,0.00,319,0

In [21]:
def lr(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_lr = LogisticRegression()
    model_lr.fit(x_train, y_train)
    preds = model_lr.predict(x_test)
    return accuracy_score(y_test, preds), f1_score(y_test, preds, average = 'macro')

In [12]:
def dtc(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_dtc = DecisionTreeClassifier()   
    model_dtc.fit(x_train, y_train)
    preds = model_dtc.predict(x_test)
    return accuracy_score(y_test, preds), f1_score(y_test, preds, average = 'macro')

In [13]:
def rfc(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_rfc = RandomForestClassifier()    
    model_rfc.fit(x_train, y_train)
    preds = model_rfc.predict(x_test)
    return accuracy_score(y_test, preds)

In [14]:
def knn(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_knn = KNeighborsClassifier()
    model_knn.fit(x_train, y_train)
    preds = model_knn.predict(x_test)
    return accuracy_score(y_test, preds)

In [15]:
def svm(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_svm = SVC(kernel = 'sigmoid')
    model_svm.fit(x_train, y_train) 
    preds = model_svm.predict(x_test)
    return accuracy_score(y_test, preds)

In [16]:
def nb(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_nb = GaussianNB()
    model_nb.fit(x_train, y_train)
    preds = model_nb.predict(x_test)
    return accuracy_score(y_test, preds)

In [17]:
def xgbb(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_xgb = xgb.XGBClassifier()
    model_xgb.fit(x_train, y_train)
    preds = model_xgb.predict(x_test)
    return accuracy_score(y_test, preds)

In [18]:
def adb(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_adb = AdaBoostClassifier()
    model_adb.fit(x_train, y_train)
    preds = model_adb.predict(x_test)
    return accuracy_score(y_test, preds)

In [19]:
def mlp(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_mlp = MLPClassifier()    
    model_mlp.fit(x_train, y_train)
    preds = model_mlp.predict(x_test)
    return accuracy_score(y_test, preds)

In [20]:
def gb(x, y):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 43)
    model_mlp = GradientBoostingClassifier() 
    model_mlp.fit(x_train, y_train)
    preds = model_mlp.predict(x_test)
    return accuracy_score(y_test, preds)

In [13]:
target = label_encoder.fit_transform(target)

In [14]:
x = df
y = target

In [15]:
x.columns = x.columns.astype('str')

In [22]:
#without feature selection


print('lr - ', lr(x, y))
print('dtc - ', dtc(x, y))
print('rfc - ', rfc(x, y))
print('knn - ', knn(x, y))
# print('svm - ', svm(x, y))
print('Naive Bayes - ', nb(x, y))
print('XGB - ', xgbb(x, y))
print('ADB - ', adb(x, y))
print('MLP - ', mlp(x, y))
print('GB - ', gb(x, y))

lr -  (0.8847233333333333, 0.25677494619615154)

C:\Users\serev\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

NameError: name 'dtc' is not defined

In [24]:
def ica(x, i):
    ica = FastICA(n_components = i, random_state = 42)
    data_ica = ica.fit_transform(x)
    data_ica = pd.DataFrame(data_ica)
    return data_ica

In [25]:
def pca(x, i):
    pca = decomposition.PCA(n_components = i, random_state=42)
    data_pca = pca.fit_transform(x)
    data_pca = pd.DataFrame(data_pca)
    return data_pca

In [26]:
def mi(x, y):
    mi = sp(percentile = 50)
    data_mi = mi.fit(x, y)
    data_mi = mi.transform(x)
    data_mi = pd.DataFrame(data_mi)
    return data_mi

In [27]:
def smf(x, y):
    lasso_model = Lasso(alpha = 0.1)
    selector = SelectFromModel(lasso_model)
    X_selected = selector.fit_transform(x, y)
    selected_features_indices = selector.get_support(indices=True)
    selected_features_names = x.columns[selected_features_indices]
    return x[selected_features_names]

In [28]:
def sfs(x, y, model):
    sfs_selector = SequentialFeatureSelector(model, forward = True, k_features = len(x.columns) // 2)
    X_selected = sfs_selector.fit_transform(x, y)
    selected_features_names = list(x.columns[sfs_selector.k_feature_idx_])
    return x[selected_features_names]

In [29]:
def rfe(x, y, model):
    rfecv_selector = RFECV(estimator = model, step = 1, cv = 5, scoring = 'accuracy')
    X_selected = rfecv_selector.fit_transform(x, y)
    selected_features_names = list(x.columns[rfecv_selector.support_])
    return x[selected_features_names]

In [30]:
def cfs(x):
    corr_matrix = x.corr()
    high_corr_features = []
    
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > 0.8:
                colname = corr_matrix.columns[i]
                high_corr_features.append(colname)

    return x.drop(high_corr_features, axis=1)

In [31]:
def fir(x, y):
    rfc = RandomForestClassifier(n_estimators=100)
    rfc.fit(x, y)
    feature_importances = list(zip(x.columns, rfc.feature_importances_))
    a = sorted(feature_importances, key=lambda x: x[1], reverse=True)
    ls = []
    for i in a[:len(a)//2 + 1]: ls.append(i[0])
    return x[ls]

In [32]:
data_ica = ica(x, len(x.columns) // 2)

C:\Users\serev\anaconda3\lib\site-packages\sklearn\decomposition\_fastica.py:542: FutureWarning: Starting in v1.3, whiten='unit-variance' will be used by default.
  warnings.warn(

In [33]:
data_pca = pca(x, len(x.columns) // 2)

In [34]:
data_mi = mi(x, y)

C:\Users\serev\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [ 6 13] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Users\serev\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: divide by zero encountered in true_divide
  f = msb / msw
C:\Users\serev\anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in true_divide
  f = msb / msw

In [35]:
data_smf = smf(x, y)

In [36]:
data_cfs = cfs(x)

In [37]:
data_fir = fir(x, y)

In [ ]:
#with feature selection ica


print('lr - ', lr(data_ica, y))
print('dtc - ', dtc(data_ica, y))
print('rfc - ', rfc(data_ica, y))
print('knn - ', knn(data_ica, y))
# print('svm - ', svm(data_ica, y))
print('Naive Bayes - ', nb(data_ica, y))
print('XGB - ', xgbb(data_ica, y))
print('ADB - ', adb(data_ica, y))
print('MLP - ', mlp(data_ica, y))
print('GB - ', gb(data_ica, y))

In [38]:
#with feature selection pca


print('lr - ', lr(data_pca, y))
print('dtc - ', dtc(data_pca, y))
print('rfc - ', rfc(data_pca, y))
print('knn - ', knn(data_pca, y))
# print('svm - ', svm(data_pca, y))
print('Naive Bayes - ', nb(data_pca, y))
print('XGB - ', xgbb(data_pca, y))
print('ADB - ', adb(data_pca, y))
print('MLP - ', mlp(data_pca, y))
print('GB - ', gb(data_pca, y))

C:\Users\serev\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

lr -  0.8738
dtc -  0.9645533333333334
rfc -  0.96457
knn -  0.9587766666666667
Naive Bayes -  0.89881
XGB -  0.96448
ADB -  0.8957333333333334
MLP -  0.9525733333333334
GB -  0.9615333333333334

In [ ]:
#with feature selection mi


print('lr - ', lr(data_mi, y))
print('dtc - ', dtc(data_mi, y))
print('rfc - ', rfc(data_mi, y))
print('knn - ', knn(data_mi, y))
# print('svm - ', svm(data_mi, y))
print('Naive Bayes - ', nb(data_mi, y))
print('XGB - ', xgbb(data_mi, y))
print('ADB - ', adb(data_mi, y))
print('MLP - ', mlp(data_mi, y))
print('GB - ', gb(data_mi, y))

In [ ]:
#with feature selection smf


print('lr - ', lr(data_smf, y))
print('dtc - ', dtc(data_smf, y))
print('rfc - ', rfc(data_smf, y))
print('knn - ', knn(data_smf, y))
# print('svm - ', svm(data_smf, y))
print('Naive Bayes - ', nb(data_smf, y))
print('XGB - ', xgbb(data_smf, y))
print('ADB - ', adb(data_smf, y))
print('MLP - ', mlp(data_smf, y))
print('GB - ', gb(data_smf, y))

In [ ]:
#with feature selection sfs


print('lr - ', lr(sfs(x, y, LogisticRegression()), y))
print('dtc - ', dtc(sfs(x, y, DecisionTreeClassifier()), y))
print('rfc - ', rfc(sfs(x, y, RandomForestClassifier()), y))
print('knn - ', knn(sfs(x, y, KNeighborsClassifier()), y))
# print('svm - ', svm(sfs(x, y, SVC(kernel = 'sigmoid')), y))
print('Naive Bayes - ', nb(sfs(x, y, GaussianNB()), y))
print('XGB - ', xgbb(sfs(x, y, xgb.XGBClassifier()), y))
print('ADB - ', adb(sfs(x, y, AdaBoostClassifier()), y))
print('MLP - ', mlp(sfs(x, y, MLPClassifier()), y))
print('GB - ', gb(sfs(x, y, GradientBoostingClassifier()), y))

In [ ]:
#with feature selection rfe


print('lr - ', lr(rfe(x, y, LogisticRegression()), y))
print('dtc - ', dtc(rfe(x, y, DecisionTreeClassifier()), y))
print('rfc - ', rfc(rfe(x, y, RandomForestClassifier()), y))
print('knn - ', knn(rfe(x, y, KNeighborsClassifier()), y))
# print('svm - ', svm(rfe(x, y, SVC(kernel = 'sigmoid')), y))
print('Naive Bayes - ', nb(rfe(x, y, GaussianNB()), y))
print('XGB - ', xgbb(rfe(x, y, xgb.XGBClassifier()), y))
print('ADB - ', adb(rfe(x, y, AdaBoostClassifier()), y))
print('MLP - ', mlp(rfe(x, y, MLPClassifier()), y))
print('GB - ', gb(rfe(x, y, GradientBoostingClassifier()), y))

In [49]:
#with feature selection csf


print('lr - ', lr(data_cfs, y))
print('dtc - ', dtc(data_cfs, y))
print('rfc - ', rfc(data_cfs, y))
print('knn - ', knn(data_cfs, y))
# print('svm - ', svm(data_cfs, y))
print('Naive Bayes - ', nb(data_cfs, y))
print('XGB - ', xgbb(data_cfs, y))
print('ADB - ', adb(data_cfs, y))
print('MLP - ', mlp(data_cfs, y))
print('GB - ', gb(data_cfs, y))

C:\Users\serev\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

lr -  0.9037333333333334
dtc -  0.96456
rfc -  0.9646566666666667
knn -  0.9590366666666666
Naive Bayes -  0.91855
XGB -  0.9646466666666667
ADB -  0.9412066666666666
MLP -  0.9503333333333334
GB -  0.9624466666666667

In [62]:
#with feature selection fir


print('lr - ', lr(data_fir, y))
print('dtc - ', dtc(data_fir, y))
print('rfc - ', rfc(data_fir, y))
print('knn - ', knn(data_fir, y))
# print('svm - ', svm(data_fir, y))
print('Naive Bayes - ', nb(data_fir, y))
print('XGB - ', xgbb(data_fir, y))
print('ADB - ', adb(data_fir, y))
print('MLP - ', mlp(data_fir, y))
print('GB - ', gb(data_fir, y))

C:\Users\serev\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

lr -  0.91088
dtc -  0.96449
rfc -  0.9646133333333333
knn -  0.9599166666666666
Naive Bayes -  0.92129
XGB -  0.9644033333333333
ADB -  0.9412066666666666
MLP -  0.95109
GB -  0.9615233333333333